name: eShopOnWeb Build and Deploy

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb-KST
  LOCATION: eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 75bc37bd-05a1-4897-94f5-0daf34087d7e
  WEBAPP-NAME: eshoponweb-webapp55318352
  AZURE_CORE_LOG_LEVEL: debug

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: |
          dotnet test ./eShopOnWeb.sln --configuration Release || echo "Ignoring non-zero exit code from tests"

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload .NET app artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload Bicep template artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download Bicep template artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: ./infra

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Template
        run: |
          az deployment group validate \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file infra/webapp.bicep \
            --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}

      - name: Deploy Azure WebApp using Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: infra/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false

      - name: Publish Website to WebApp using CLI
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP-NAME }} \
              --resource-group ${{ env.RESOURCE-GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
